#!/bin/bash

# Render Environment Variables Setup Script
# This script helps configure environment variables for Spark backend on Render

echo "🔧 Spark Backend - Render Environment Variables Setup"
echo "====================================================="
echo ""

# Configuration from config.json
SALT="a2dac101827c8d47f00831f2d6c078b2"
ADMIN_HASH="$2b$10$RYCAuSMeNE1uh2/qka5PSeE6RFjynbpXu95HMStXmUHA8qaQNBFjG"
PORT="8000"
GO_ENV="production"

echo "📋 Required Environment Variables:"
echo "=================================="
echo ""
echo "1. PORT"
echo "   Value: $PORT"
echo "   Purpose: Port for the server to listen on"
echo ""
echo "2. GO_ENV"
echo "   Value: $GO_ENV"
echo "   Purpose: Sets Go environment to production mode"
echo ""
echo "3. SPARK_SALT"
echo "   Value: $SALT"
echo "   Purpose: 32-character salt for packet encryption"
echo ""
echo "4. SPARK_ADMIN_HASH"
echo "   Value: $ADMIN_HASH"
echo "   Purpose: Bcrypt hash of admin password"
echo ""

echo "🚀 How to Set These in Render Dashboard:"
echo "======================================="
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Find your 'spark-backend-fixed-v2' service"
echo "3. Click on the service name"
echo "4. Click on 'Environment' tab"
echo "5. Click 'Add Environment Variable' for each variable above"
echo "6. Enter the exact variable name and value"
echo "7. Click 'Save Changes'"
echo "8. The service will automatically redeploy"
echo ""

echo "🔍 Verification Steps:"
echo "====================="
echo ""
echo "After setting the variables and deploying:"
echo ""
echo "1. Check Render logs for:"
echo "   - 'Server starting on port 8000'"
echo "   - 'Salt loaded from environment'"
echo "   - 'Admin auth configured'"
echo ""
echo "2. Test health endpoint:"
echo "   curl https://spark-backend-fixed-v2.onrender.com/api/info"
echo ""
echo "3. Expected response:"
echo "   {\"version\":\"1.0.0\",\"uptime\":\"5s\",\"clients\":0}"
echo ""

echo "⚠️  Security Notes:"
echo "=================="
echo ""
echo "- SPARK_SALT: Used to encrypt all client-server communication"
echo "- SPARK_ADMIN_HASH: Bcrypt hash of admin password"
echo "- Never commit these values to Git"
echo "- Rotate these values every 90 days"
echo "- Use different values for production vs development"
echo ""

echo "🐛 Troubleshooting:"
echo "=================="
echo ""
echo "- Server won't start: Check all environment variables are set correctly"
echo "- Authentication fails: Verify SPARK_ADMIN_HASH matches config.json"
echo "- Client can't connect: Verify SPARK_SALT matches client configuration"
echo "- Port binding error: Ensure PORT=8000 is set"
echo ""

echo "✅ Environment Variables Setup Complete!"
echo "======================================="
echo ""
echo "Next steps:"
echo "1. Set the variables in Render dashboard"
echo "2. Wait for automatic redeployment"
echo "3. Test the health endpoint"
echo "4. Configure frontend to connect to backend"
echo "5. Build and distribute clients with matching salt"
echo ""
echo "Your Spark backend will be available at:"
echo "https://spark-backend-fixed-v2.onrender.com"